#!/usr/bin/env bash

#------------------------------------------------
#Create the sh programming code for the abs-guide
#Tarek Ibrahim
#tarekmohamedibrahim@gmail.com
#Cairo, 2022-Feb
#------------------------------------------------

find -name '*.html' -exec ./py-find.py {} \;
sudo chown `whoami`:`whoami` *.sh
sudo chmod +x *.sh
vim abs-guide.sh

